/*
 * Copyright (c) Juniper Networks, Inc. All rights reserved.
 */

module.exports = {
  ColorPickerConfigModel: require('components/color-picker/ColorPickerConfigModel'),
  ColorPickerView: require('components/color-picker/ColorPickerView'),
  CompositeYChartConfigModel: require('components/composite-y/CompositeYChartConfigModel'),
  CompositeYChartView: require('components/composite-y/CompositeYChartView'),
  ControlPanelConfigModel: require('components/control-panel/ControlPanelConfigModel'),
  ControlPanelView: require('components/control-panel/ControlPanelView'),
  CrosshairConfigModel: require('components/crosshair/CrosshairConfigModel'),
  CrosshairView: require('components/crosshair/CrosshairView'),
  FilterView: require('components/filter/FilterView'),
  FilterConfigModel: require('components/filter/FilterConfigModel'),
  LegendConfigModel: require('components/legend/LegendConfigModel'),
  LegendView: require('components/legend/LegendView'),
  LegendUniversalConfigModel: require('components/legend-universal/LegendConfigModel'),
  LegendUniversalView: require('components/legend-universal/LegendView'),
  LegendPanelConfigModel: require('components/legend-panel/LegendPanelConfigModel'),
  LegendPanelView: require('components/legend-panel/LegendPanelView'),
  MessageConfigModel: require('components/message/MessageConfigModel'),
  MessageView: require('components/message/MessageView'),
  NavigationConfigModel: require('components/navigation/NavigationConfigModel'),
  NavigationView: require('components/navigation/NavigationView'),
  PieChartConfigModel: require('components/pie-chart/PieChartConfigModel'),
  PieChartView: require('components/pie-chart/PieChartView'),
  RadialDendrogramConfigModel: require('components/radial/RadialDendrogramConfigModel'),
  RadialDendrogramView: require('components/radial/RadialDendrogramView'),
  StandaloneConfigModel: require('components/standalone/StandaloneConfigModel'),
  StandaloneView: require('components/standalone/StandaloneView'),
  TimelineConfigModel: require('components/timeline/TimelineConfigModel'),
  TimelineView: require('components/timeline/TimelineView'),
  TooltipConfigModel: require('components/tooltip/TooltipConfigModel'),
  TooltipView: require('components/tooltip/TooltipView'),
}
